-- 1. CREAR UNA BASE DATOS

-- DROP DATABASE IF EXISTS IMPORTEPRODUCTO;
-- CREATE DATABASE IMPORTEPRODUCTO;

-- 2. USAR UNA BASE DE DATOS

-- USE IMPORTEPRODUCTO;

-- 3. CREAR UNA TABLA

DROP TABLE IF EXISTS Factura;

CREATE TABLE IF NOT EXISTS Factura (
  idFactura             SERIAL NOT NULL,
  cantidadCajas INT            NOT NULL,
  unidadesxCaja INT            NOT NULL,
  precioxUnidad DECIMAL        NOT NULL,
                PRIMARY KEY (idFactura)
);

-- 4. MOSTRAR LAS TABLAS DE UNA BASE DE DATOS

-- SHOW TABLES;

-- 5. DESCRBIR UNA TABLE

-- DESCRIBE Factura;

-- 6. INSERTAR REGISTRO EN UNA TABLA

-- 7. MOSTRAR TODOS LOS REGISTROS DE UNA TABLA

SELECT * FROM Factura;

