/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing01;

import javax.swing.JOptionPane;

/**
 *
 * @author RYZEN
 */
public class Ventana2 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana2
     */
    public Ventana2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cntPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        txtEntrada = new javax.swing.JTextField();
        cmdNombre = new javax.swing.JButton();
        cmdAyuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("NOMBRES Y APELLIDOS");
        lblTitulo.setOpaque(true);

        txtEntrada.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cmdNombre.setBackground(new java.awt.Color(0, 0, 0));
        cmdNombre.setForeground(new java.awt.Color(255, 255, 0));
        cmdNombre.setText("PONER NOMBRE");
        cmdNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNombreActionPerformed(evt);
            }
        });

        cmdAyuda.setText("AYUDA");
        cmdAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAyudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cntPrincipalLayout = new javax.swing.GroupLayout(cntPrincipal);
        cntPrincipal.setLayout(cntPrincipalLayout);
        cntPrincipalLayout.setHorizontalGroup(
            cntPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtEntrada)
            .addComponent(cmdNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(cntPrincipalLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(cmdAyuda)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        cntPrincipalLayout.setVerticalGroup(
            cntPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cntPrincipalLayout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(cmdNombre)
                .addGap(40, 40, 40)
                .addComponent(cmdAyuda))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cntPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cntPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNombreActionPerformed
        String entrada = txtEntrada.getText();
        String patron = "[a-zA-ZáéíóúÑñ\\s]+";
        boolean correcto = entrada.matches(patron);
        if (correcto) {
            lblTitulo.setText(entrada);
        } else {
            System.out.println("DEBE INGRESEAR SU NOMBRE");
            JOptionPane.showMessageDialog(this,"DEBE INGRESAR SU NOMBRE","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cmdNombreActionPerformed

    private void cmdAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAyudaActionPerformed
        JOptionPane.showMessageDialog(this,"Su nombres y apellidos deberá contener sólo letras","AYUDA",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_cmdAyudaActionPerformed

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAyuda;
    private javax.swing.JButton cmdNombre;
    private javax.swing.JPanel cntPrincipal;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtEntrada;
    // End of variables declaration//GEN-END:variables
}
