-- 3. CREAR UNA TABLA

CREATE TABLE IF NOT EXISTS Factura (
  idFactura     INTEGER    NOT NULL PRIMARY KEY AUTOINCREMENT,
  cantidadCajas INTEGER    NOT NULL,
  unidadesxCaja INTEGER    NOT NULL,
  precioxUnidad DOUBLE NOT NULL
);

-- 7. MOSTRAR TODOS LOS REGISTROS DE UNA TABLA

SELECT * FROM Factura;

